# Generated by Django 5.2.17 on 2026-09-17 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_link', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cta/')),
            ],
            options={
                'verbose_name': 'CTA Section',
                'verbose_name_plural': 'CTA Section',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(choices=[('quick_links', 'Quick Links'), ('ride_options', 'Ride Options'), ('support', 'Support')], max_length=30)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'ordering': ['group_name', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_line1', models.CharField(help_text='e.g. Your Ride.', max_length=100)),
                ('heading_line2', models.CharField(help_text='e.g. Your Way. (highlighted)', max_length=100)),
                ('subtext', models.TextField(blank=True)),
                ('button1_text', models.CharField(blank=True, max_length=50)),
                ('button1_link', models.CharField(blank=True, max_length=200)),
                ('button2_text', models.CharField(blank=True, max_length=50)),
                ('button2_link', models.CharField(blank=True, max_length=200)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='HowItWorksStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='how_it_works/')),
            ],
            options={
                'verbose_name': 'How It Works Step',
                'verbose_name_plural': 'How It Works Steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='JourneyBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=150)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='journey_banner/')),
            ],
            options={
                'verbose_name': 'Journey Banner',
                'verbose_name_plural': 'Journey Banner',
            },
        ),
        migrations.CreateModel(
            name='SafetySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='safety/')),
                ('badge_text', models.CharField(blank=True, help_text='e.g. Safety, every mile', max_length=50)),
            ],
            options={
                'verbose_name': 'Safety Section',
                'verbose_name_plural': 'Safety Section',
            },
        ),
        migrations.CreateModel(
            name='SectionHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('choose_ride', 'Choose the Ride'), ('how_it_works', 'How It Works')], max_length=30, unique=True)),
                ('heading', models.CharField(max_length=150)),
                ('subtext', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'Section Heading',
                'verbose_name_plural': 'Section Headings',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Travu', max_length=100)),
                ('tagline', models.CharField(blank=True, help_text='e.g. Every Miles matters', max_length=150)),
                ('unit_of_text', models.CharField(blank=True, help_text='e.g. A unit of Blue Holidays', max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('primary_phone_number', models.CharField(help_text='Click-to-call number', max_length=20)),
                ('secondary_phone_number', models.CharField(blank=True, max_length=20)),
                ('whatsapp_number', models.CharField(help_text='Include country code, e.g. 91XXXXXXXXXX', max_length=20)),
                ('email', models.EmailField(help_text='Used for floating icon and as contact-form recipient', max_length=254)),
                ('address', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('extra_luggage_note', models.TextField(blank=True, help_text="Shown under the booking form on every booking, e.g. 'Travelling with extra luggage?'")),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Sedan, Tempo Traveller 12 Seater', max_length=100)),
                ('models_text', models.CharField(blank=True, help_text='e.g. Swift Dzire, Honda Amaze, Toyota Etios', max_length=200)),
                ('seating_capacity', models.PositiveIntegerField()),
                ('ideal_for', models.CharField(blank=True, max_length=150)),
                ('luggage_capacity', models.CharField(blank=True, max_length=150)),
                ('configuration_note', models.CharField(blank=True, help_text='e.g. captain seats vs bench seat in middle row', max_length=200)),
                ('ac_available_in_hills', models.BooleanField(default=False, help_text='AC logic to be finalized during development')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('badge', models.CharField(blank=True, help_text='e.g. Most Popular, Best Value (leave blank for none)', max_length=50)),
                ('local_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('outstation_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('per_km_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('driver_allowance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text="Shown by default in Choose the Ride section (rest under 'View All')")),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'verbose_name_plural': 'Vehicle Types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Google Material Icon name, e.g. bolt, payments, verified_user, support_agent', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Why Choose Us Feature',
                'verbose_name_plural': 'Why Choose Us Features',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_link', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Why Choose Us Section',
                'verbose_name_plural': 'Why Choose Us Section',
            },
        ),
        migrations.CreateModel(
            name='BookingEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('trip_type', models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip')], default='one_way', max_length=20)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('passengers', models.PositiveIntegerField(default=1)),
                ('full_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='core.vehicletype')),
            ],
            options={
                'verbose_name': 'Booking Enquiry',
                'verbose_name_plural': 'Booking Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
