# Generated by Django 5.2.17 on 2026-09-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='ac_available_in_hills',
            field=models.BooleanField(default=False, help_text='Tick this ONLY if this vehicle has AC running even on hill station routes. Leave unticked for regular routes/rules (ask the developer if unsure).', verbose_name='AC available in hill stations'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='badge',
            field=models.CharField(blank=True, help_text='Small highlight label shown on the card, e.g. Most Popular, Best Value. Leave blank to show no badge.', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='configuration_note',
            field=models.CharField(blank=True, help_text='Optional extra seating detail, only needed for a few vehicles. e.g. Captain seats in middle row. Leave blank if not applicable.', max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Controls the order vehicles appear in on the website. Lower numbers show first (e.g. 1 appears before 2).'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='driver_allowance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily driver allowance/bata (in Rs.) for outstation trips. Leave blank if not decided yet.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='ideal_for',
            field=models.CharField(blank=True, help_text='A short line telling customers who this vehicle suits. e.g. Small family / 2-3 guests', max_length=150),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a clear photo of this vehicle. Recommended: landscape photo, under 2MB, JPG or PNG.', null=True, upload_to='vehicles/'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Tick this to show this vehicle immediately in the 'Choose the Ride' section. Untick to hide it behind the 'View All' button instead.", verbose_name='Show by default on website'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='local_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price (in Rs.) for a local/half-day booking of this vehicle. Leave blank if not decided yet.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='luggage_capacity',
            field=models.CharField(blank=True, help_text='A short line describing how much luggage fits. e.g. Approx. 2-3 medium bags', max_length=150),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='models_text',
            field=models.CharField(blank=True, help_text='List the actual car model names for this vehicle type, separated by commas. e.g. Swift Dzire, Honda Amaze, Toyota Etios. Leave blank if not applicable.', max_length=200, verbose_name='Car models'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='name',
            field=models.CharField(help_text="This is the vehicle's title shown to customers on the website. e.g. Sedan, Tempo Traveller 12 Seater", max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='outstation_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price (in Rs.) for a full-day/outstation booking of this vehicle. Leave blank if not decided yet.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='per_km_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price (in Rs.) charged per kilometre travelled. Leave blank if not decided yet.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='seating_capacity',
            field=models.PositiveIntegerField(help_text='Number of passenger seats (not counting the driver). e.g. 4'),
        ),
    ]
