# Generated by Django 5.2.17 on 2026-09-17 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_vehicletype_ac_available_in_hills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingenquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this enquiry was submitted.'),
        ),
        migrations.AlterField(
            model_name='bookingenquiry',
            name='destination',
            field=models.CharField(help_text='Where the customer wants to go.', max_length=255),
        ),
        migrations.AlterField(
            model_name='bookingenquiry',
            name='email',
            field=models.EmailField(blank=True, help_text="Customer's email, if provided.", max_length=254),
        ),
        migrations.AlterField(
            model_name='bookingenquiry',
            name='full_name',
            field=models.CharField(help_text="Customer's name.", max_length=100),
        ),
        migrations.AlterField(
            model_name='bookingenquiry',
            name='mobile_number',
            field=models.CharField(help_text="Customer's mobile number.", max_length=15),
        ),
        migrations.AlterField(
            model_name='bookingenquiry',
            name='passengers',
            field=models.PositiveIntegerField(default=1, help_text='Number of passengers travelling.'),
        ),
        migrations.AlterField(
            model_name='bookingenquiry',
            name='pickup_date',
            field=models.DateField(help_text='Date the customer wants to travel.'),
        ),
        migrations.AlterField(
            model_name='bookingenquiry',
            name='pickup_location',
            field=models.CharField(help_text='Where the customer wants to be picked up.', max_length=255),
        ),
        migrations.AlterField(
            model_name='bookingenquiry',
            name='pickup_time',
            field=models.TimeField(help_text='Time the customer wants to be picked up.'),
        ),
        migrations.AlterField(
            model_name='bookingenquiry',
            name='trip_type',
            field=models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip')], default='one_way', help_text='One way or round trip.', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingenquiry',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, help_text='Vehicle the customer selected, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='core.vehicletype'),
        ),
        migrations.AlterField(
            model_name='ctasection',
            name='button_link',
            field=models.CharField(blank=True, help_text='Where the button goes to. Ask the developer if unsure.', max_length=200),
        ),
        migrations.AlterField(
            model_name='ctasection',
            name='button_text',
            field=models.CharField(blank=True, help_text='Text on the button. e.g. Book Your Cab', max_length=50),
        ),
        migrations.AlterField(
            model_name='ctasection',
            name='description',
            field=models.TextField(blank=True, help_text='Short paragraph under the heading.'),
        ),
        migrations.AlterField(
            model_name='ctasection',
            name='heading',
            field=models.CharField(blank=True, help_text='Heading for the closing call-to-action section. e.g. Ready to Ride?', max_length=150),
        ),
        migrations.AlterField(
            model_name='ctasection',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo shown alongside this section.', null=True, upload_to='cta/'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Controls the order links appear in within their column. Lower numbers show first.'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='group_name',
            field=models.CharField(choices=[('quick_links', 'Quick Links'), ('ride_options', 'Ride Options'), ('support', 'Support')], help_text='Which footer column this link appears under.', max_length=30),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='label',
            field=models.CharField(help_text='The link text customers see. e.g. Contact Us', max_length=100),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='url',
            field=models.CharField(help_text='Where this link goes to. Ask the developer if unsure.', max_length=200),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Large background photo behind the heading. Use a wide, high-quality photo.', null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button1_link',
            field=models.CharField(blank=True, help_text='Where the first button goes to. Ask the developer if unsure.', max_length=200),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button1_text',
            field=models.CharField(blank=True, help_text='Text on the first button. e.g. Book a Cab', max_length=50),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button2_link',
            field=models.CharField(blank=True, help_text='Where the second button goes to. Ask the developer if unsure.', max_length=200),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button2_text',
            field=models.CharField(blank=True, help_text='Text on the second button. e.g. View Ride Options', max_length=50),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='heading_line1',
            field=models.CharField(help_text='First line of the big heading at the top of the website. e.g. Your Ride.', max_length=100),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='heading_line2',
            field=models.CharField(help_text='Second line of the heading, shown in the highlight colour. e.g. Your Way.', max_length=100),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='subtext',
            field=models.TextField(blank=True, help_text='Short paragraph under the heading explaining what you offer.'),
        ),
        migrations.AlterField(
            model_name='howitworksstep',
            name='description',
            field=models.TextField(blank=True, help_text='One line explaining this step to the customer.'),
        ),
        migrations.AlterField(
            model_name='howitworksstep',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo shown alongside this step.', null=True, upload_to='how_it_works/'),
        ),
        migrations.AlterField(
            model_name='howitworksstep',
            name='step_number',
            field=models.PositiveIntegerField(help_text='Order this step appears in. e.g. 1, 2, 3'),
        ),
        migrations.AlterField(
            model_name='howitworksstep',
            name='title',
            field=models.CharField(help_text='Short title for this step. e.g. Enter Your Trip', max_length=100),
        ),
        migrations.AlterField(
            model_name='journeybanner',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Large background photo for this banner. Use a wide, high-quality photo.', null=True, upload_to='journey_banner/'),
        ),
        migrations.AlterField(
            model_name='journeybanner',
            name='heading',
            field=models.CharField(blank=True, help_text='Heading shown over the journey banner photo.', max_length=150),
        ),
        migrations.AlterField(
            model_name='safetysection',
            name='badge_text',
            field=models.CharField(blank=True, help_text='Small highlight label shown on the photo. e.g. Safety, every mile', max_length=50),
        ),
        migrations.AlterField(
            model_name='safetysection',
            name='description',
            field=models.TextField(blank=True, help_text='Short paragraph describing your safety measures.'),
        ),
        migrations.AlterField(
            model_name='safetysection',
            name='heading',
            field=models.CharField(blank=True, help_text='Heading for the safety section.', max_length=150),
        ),
        migrations.AlterField(
            model_name='safetysection',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo shown alongside this section.', null=True, upload_to='safety/'),
        ),
        migrations.AlterField(
            model_name='sectionheading',
            name='heading',
            field=models.CharField(help_text='The heading text shown above this section.', max_length=150),
        ),
        migrations.AlterField(
            model_name='sectionheading',
            name='section_key',
            field=models.CharField(choices=[('choose_ride', 'Choose the Ride'), ('how_it_works', 'How It Works')], help_text='Which section on the website this heading belongs to.', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='sectionheading',
            name='subtext',
            field=models.CharField(blank=True, help_text='Optional short line shown under the heading.', max_length=250),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, help_text='Full business address, shown in the footer.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_name',
            field=models.CharField(default='Travu', help_text='Your business name as shown across the website. e.g. Travu', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(help_text='Business email shown on the website and used as the contact address.', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='extra_luggage_note',
            field=models.TextField(blank=True, help_text="A short note shown under the booking form on every booking, reminding customers to mention extra luggage. e.g. 'Travelling with extra luggage? Let us know in advance.'"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Link to your Facebook page. Leave blank to hide the icon.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Link to your Instagram page. Leave blank to hide the icon.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload your logo image. Use a transparent PNG for best results.', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_phone_number',
            field=models.CharField(help_text='Main phone number. Customers can tap this on the website to call you directly.', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_phone_number',
            field=models.CharField(blank=True, help_text='Optional second phone number. Leave blank if not needed.', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(blank=True, help_text='Short slogan shown near the logo. e.g. Every Miles matters', max_length=150),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='unit_of_text',
            field=models.CharField(blank=True, help_text='Small text under the brand name. e.g. A unit of Blue Holidays', max_length=150, verbose_name='Parent company line'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(help_text='WhatsApp number including country code, no spaces or symbols. e.g. 918148664196', max_length=20),
        ),
        migrations.AlterField(
            model_name='whychooseusfeature',
            name='description',
            field=models.TextField(blank=True, help_text='One line explaining this feature.'),
        ),
        migrations.AlterField(
            model_name='whychooseusfeature',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Controls the order these show in. Lower numbers show first.'),
        ),
        migrations.AlterField(
            model_name='whychooseusfeature',
            name='icon',
            field=models.CharField(help_text='Google Material Icon name (ask the developer for the exact name to use). e.g. bolt, payments, verified_user, support_agent', max_length=50),
        ),
        migrations.AlterField(
            model_name='whychooseusfeature',
            name='title',
            field=models.CharField(help_text='Short title for this feature. e.g. Fast Booking', max_length=100),
        ),
        migrations.AlterField(
            model_name='whychooseussection',
            name='button_link',
            field=models.CharField(blank=True, help_text='Where the button goes to. Ask the developer if unsure.', max_length=200),
        ),
        migrations.AlterField(
            model_name='whychooseussection',
            name='button_text',
            field=models.CharField(blank=True, help_text='Text on the button in this section.', max_length=50),
        ),
        migrations.AlterField(
            model_name='whychooseussection',
            name='description',
            field=models.TextField(blank=True, help_text='Short paragraph under the heading.'),
        ),
        migrations.AlterField(
            model_name='whychooseussection',
            name='heading',
            field=models.CharField(blank=True, help_text="Heading for the 'why choose us' section.", max_length=150),
        ),
    ]
