# Generated by Django 5.2.17 on 2026-09-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_bookingenquiry_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='availability_text',
            field=models.CharField(blank=True, help_text='Small availability note shown top-right of the card, e.g. Available Now in Kanyakumari. Leave blank to hide.', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='has_ac',
            field=models.BooleanField(default=True, help_text="Tick to show a 'Climate AC' tag on the card.", verbose_name='Has climate AC'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='has_audio_usb',
            field=models.BooleanField(default=True, help_text="Tick to show an 'Audio & USB' tag on the card.", verbose_name='Has audio & USB'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='image_badge_text',
            field=models.CharField(blank=True, help_text='Small label shown on top of the vehicle photo, e.g. Sedan AC. Leave blank for none.', max_length=50, verbose_name='Photo label'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Star rating out of 5, e.g. 4.9. Leave blank to hide the rating.', max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='review_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of reviews behind the rating, e.g. 420. Leave blank to hide.', null=True),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='local_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price (in Rs.) for a local/half-day booking of this vehicle. Leave blank if not decided yet.', max_digits=10, null=True, verbose_name='Local / half day rate'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='outstation_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price (in Rs.) for a full-day sightseeing booking of this vehicle. Leave blank if not decided yet.', max_digits=10, null=True, verbose_name='Full day / sightseeing rate'),
        ),
    ]
