# Generated by Django 5.2.17 on 2026-09-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vehicletype_availability_text_vehicletype_has_ac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='description',
            field=models.TextField(blank=True, help_text='A longer sentence or two describing this vehicle, shown in the card body. e.g. Air-conditioned 4+1 seater with superior boot space, perfect for local sunset points...'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='ideal_for',
            field=models.CharField(blank=True, help_text='A short line telling customers who this vehicle suits, shown next to the badge at the top of the card. e.g. Small family / 2-3 guests', max_length=150),
        ),
    ]
