# Generated by Django 5.2.17 on 2026-09-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_vehicletype_description_alter_vehicletype_ideal_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='local_rate_note',
            field=models.CharField(blank=True, help_text='Small note shown under the local rate, e.g. 4 hrs / 40 km. Leave blank for none.', max_length=50, verbose_name='Local / half day note'),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='outstation_rate_note',
            field=models.CharField(blank=True, help_text='Small note shown under the full day rate, e.g. 8 hrs / 80 km. Leave blank for none.', max_length=50, verbose_name='Full day / sightseeing note'),
        ),
    ]
