# Generated by Django 5.2.17 on 2026-09-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vehicletype_local_rate_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='background_image_2',
            field=models.ImageField(blank=True, help_text='Optional second photo. If set, the background slowly crossfades between the two photos. Leave blank to show only the first photo.', null=True, upload_to='hero/', verbose_name='Second background photo'),
        ),
    ]
