# Generated by Django 5.2.17 on 2026-09-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_ctasection_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hill_station_note',
            field=models.TextField(blank=True, help_text='Note about AC availability on hill station routes. Shown in the booking confirmation email. Leave blank to hide.', verbose_name='Hill station AC note'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='travel_guidelines',
            field=models.TextField(blank=True, help_text='Travel & driver guidelines (KM/time calculation, driver duty, hill station timing, etc). One point per line. Shown in the booking confirmation email. Leave blank to hide.'),
        ),
    ]
