# Generated by Django 5.2.17 on 2026-09-18 05:57

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesettings_hill_station_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctasection',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo shown alongside this section (max 20MB).', null=True, upload_to='cta/', validators=[core.validators.validate_image_max_size]),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Large background photo behind the heading (max 20MB). Use a wide, high-quality photo.', null=True, upload_to='hero/', validators=[core.validators.validate_image_max_size]),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='background_image_2',
            field=models.ImageField(blank=True, help_text='Optional second photo (max 20MB). If set, the background slowly crossfades between the two photos. Leave blank to show only the first photo.', null=True, upload_to='hero/', validators=[core.validators.validate_image_max_size], verbose_name='Second background photo'),
        ),
        migrations.AlterField(
            model_name='howitworksstep',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo shown alongside this step (max 20MB).', null=True, upload_to='how_it_works/', validators=[core.validators.validate_image_max_size]),
        ),
        migrations.AlterField(
            model_name='journeybanner',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Large background photo for this banner (max 20MB). Use a wide, high-quality photo.', null=True, upload_to='journey_banner/', validators=[core.validators.validate_image_max_size]),
        ),
        migrations.AlterField(
            model_name='safetysection',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo shown alongside this section (max 20MB).', null=True, upload_to='safety/', validators=[core.validators.validate_image_max_size]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload your logo image (max 20MB). Use a transparent PNG for best results.', null=True, upload_to='site/', validators=[core.validators.validate_image_max_size]),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a clear photo of this vehicle. Recommended: landscape photo, under 20MB, JPG or PNG.', null=True, upload_to='vehicles/', validators=[core.validators.validate_image_max_size]),
        ),
    ]
