# Generated by Django 5.2.17 on 2026-09-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_ctasection_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_url',
            field=models.URLField(blank=True, help_text='Link to your Google Business profile/reviews page. Leave blank to hide the icon.'),
        ),
    ]
