# Generated by Django 5.2.17 on 2026-09-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_vehicletype_availability_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short safety point shown with a checkmark. e.g. Driver Verification', max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls the order these show in. Lower numbers show first.')),
            ],
            options={
                'verbose_name': 'Safety Point',
                'verbose_name_plural': 'Safety Points',
                'ordering': ['display_order'],
            },
        ),
    ]
