# Generated by Django 5.2.17 on 2026-09-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_safety_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='group_name',
            field=models.CharField(choices=[('quick_links', 'Quick Links'), ('ride_options', 'Ride Options')], help_text='Which footer column this link appears under.', max_length=30),
        ),
    ]
