# Generated by Django 5.2.17 on 2026-09-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_footer_support_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Customer's name.", max_length=100)),
                ('email', models.EmailField(blank=True, help_text="Customer's email, if provided.", max_length=254)),
                ('mobile_number', models.CharField(help_text="Customer's mobile number.", max_length=15)),
                ('message', models.TextField(help_text='What the customer wants to ask or tell you.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this message was submitted.')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
