# Generated by Django 5.2.17 on 2026-09-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='heading_line2',
            field=models.CharField(blank=True, help_text='Second line of the heading, shown in the highlight colour. e.g. Your Way. Leave blank to show only the first line.', max_length=100),
        ),
    ]
