# Generated by Django 5.2.17 on 2026-09-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_hero_heading_line2_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionheading',
            name='eyebrow',
            field=models.CharField(blank=True, help_text='Small label shown above the heading, usually in caps. e.g. The Journey Starts Here', max_length=100),
        ),
    ]
