# Generated by Django 5.2.17 on 2026-09-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_section_heading_eyebrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='whychooseussection',
            name='eyebrow',
            field=models.CharField(blank=True, help_text='Small label shown above the heading, usually in caps. e.g. Why Choose Travu', max_length=100),
        ),
    ]
