# Generated by Django 5.2.17 on 2026-09-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_why_choose_us_eyebrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeybanner',
            name='description',
            field=models.TextField(blank=True, help_text='Short paragraph shown under the heading.'),
        ),
        migrations.AddField(
            model_name='journeybanner',
            name='eyebrow',
            field=models.CharField(blank=True, help_text='Small label shown above the heading, usually in caps. e.g. Where Will The Road Take You?', max_length=100),
        ),
    ]
