# Generated by Django 5.2.17 on 2026-09-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_journey_banner_eyebrow_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetypoint',
            name='description',
            field=models.CharField(blank=True, help_text='One line explaining this point. e.g. Professional drivers focused on safe and responsible travel. Leave blank to show just the title.', max_length=200),
        ),
        migrations.AddField(
            model_name='safetysection',
            name='button_link',
            field=models.CharField(blank=True, help_text='Where the button goes to. Ask the developer if unsure.', max_length=200),
        ),
        migrations.AddField(
            model_name='safetysection',
            name='button_text',
            field=models.CharField(blank=True, help_text='Text on the button below the safety points. e.g. Travel With Confidence', max_length=50),
        ),
        migrations.AlterField(
            model_name='safetypoint',
            name='title',
            field=models.CharField(help_text='Short safety point shown with a checkmark. e.g. Trusted Drivers', max_length=100),
        ),
    ]
