# Generated by Django 5.2.17 on 2026-09-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_safety_point_description_cta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctasection',
            name='eyebrow',
            field=models.CharField(blank=True, help_text='Small label shown above the heading. e.g. One Click. One Ride. One More Journey.', max_length=100),
        ),
    ]
