# Generated by Django 5.2.17 on 2026-09-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_cta_section_eyebrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The question, as a customer would ask it.', max_length=200)),
                ('answer', models.TextField(help_text='The answer shown when the question is expanded.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls the order these show in. Lower numbers show first.')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['display_order'],
            },
        ),
    ]
